### ISSUE TITLE
cannot load such file -- reflekt (LoadError)

### ISSUE THREAD

**Issue by greyblake** [refIekt/reflekt#2]
Hi, 
I'd like to give it a try and play with Reflekt. The idea seems to be very promising!

The doc and demo example says `require "reflekt"`, but `reflekt` file is not found.

The reason for this is because the library names the file `Reflekt.rb` instead of `reflekt.rb`.

I don't know if that is on purpose of not, but `Reflekt.rb` looks very weird and is not idiomatic for Ruby.

**Comment by maedi** [comment]
Thanks @greyblake looking into this...

**Comment by maedi** [comment]
@greyblake I've snake cased all of the filenames and made the requires relative so that the demo works without first running `gem install reflekt`. It's released as 1.0.6 or you can git pull. How's that now?

**Comment by maedi** [comment]
Actually you will still need to run `gem install reflekt` to install dependencies. I will update the demo steps to include this. For anything other than demo I'm currently recommending a Gemfile and `bundle install` approach, but might add `gem install reflekt` just to make things simpler for people with simple scripts.

**Comment by greyblake** [comment]
Thanks!
`bundle install` VS `gem install reflekt` - both are common and well known.
Whatever it is, it will not cause any problems for rubists :)
