### ISSUE TITLE
PR_END_OF_FILE_ERROR on https://reflekt.dev/

### ISSUE THREAD

**Issue by benoittgt** [refIekt/reflekt#9]

**Comment by maedi** [comment]
Hey @benoittgt I see you're in the RSpec core team :) Maybe one day Reflekt could export to RSpec?

**Comment by benoittgt** [comment]
We have to speak about it with Jon the lead maintainer. :)

The link properly resolved to the Github repo now. 🎉

**Comment by maedi** [comment]
@benoittgt Just a heads up that the website is now live: https://reflekt.dev/
